### ISSUE TITLE
Default storage class

### ISSUE THREAD

**Issue by mxmxchere** [SovereignCloudStack/moin-cluster-config#43]
Kamaji and the monitoring stack use persistent volumes. I have manually set `csi-cinder-sc-delete` as default class. Either we have to set a default class via Git or we have to set explicit storageclasses per persistent volume. The downside with the latter approach is that we assume to have storage class x in a cluster which we currently have no reason to assume.

**Comment by chess-knight** [comment]
In the KaaS v1, there is a default storage class https://github.com/SovereignCloudStack/k8s-cluster-api-provider/blob/main/terraform/files/kubernetes-manifests.d/cinder-provider.yaml so that we can set it also in the KaaS v2. It shouldn't be a problem via cluster-addon helm values see https://github.com/kubernetes/cloud-provider-openstack/blob/master/charts/cinder-csi-plugin/templates/storageclass.yaml, e.g. set `.Values.storageClass.delete.isDefault` to `true`.

**Comment by chess-knight** [comment]
Related standard https://github.com/SovereignCloudStack/standards/issues/652
